url: "https://compliancepack.net/"

compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "article"
    values:
      layout: "article"

sass:
  sourcemap: never
