url: "https://compliance-resource-pack.github.io/"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "article/compliance64x"
    values:
      layout: "article"
  - scope:
      path: "article/compliance32x"
    values:
      layout: "article"